<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="540" started-at="2015-03-29T19:00:57Z" finished-at="2015-03-29T19:00:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="540" started-at="2015-03-29T19:00:57Z" finished-at="2015-03-29T19:00:58Z">
      <class name="bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest">
        <test-method status="PASS" signature="EventEvent()[pri:0, instance:bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest@18e8568]" name="EventEvent" duration-ms="35" started-at="2015-03-29T21:00:57Z" finished-at="2015-03-29T21:00:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EventEvent -->
        <test-method status="PASS" signature="impact()[pri:0, instance:bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest@18e8568]" name="impact" duration-ms="37" started-at="2015-03-29T21:00:58Z" finished-at="2015-03-29T21:00:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- impact -->
        <test-method status="PASS" signature="testtoString()[pri:0, instance:bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest@18e8568]" name="testtoString" duration-ms="64" started-at="2015-03-29T21:00:58Z" finished-at="2015-03-29T21:00:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtoString -->
        <test-method status="FAIL" signature="testtoString2()[pri:0, instance:bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest@18e8568]" name="testtoString2" duration-ms="349" started-at="2015-03-29T21:00:58Z" finished-at="2015-03-29T21:00:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [cool artist @ my Venue on 09.03.2015
my fancy description
(250 attending (500))] but found [cool artist @ my Venue on 01.01.1970
my fancy description
(250 attending (500))]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [cool artist @ my Venue on 09.03.2015
my fancy description
(250 attending (500))] but found [cool artist @ my Venue on 01.01.1970
my fancy description
(250 attending (500))]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest.testtoString2(EventTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtoString2 -->
      </class> <!-- bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
